# Retrieve basic information about employees in department 101

SELECT employee_id, first_name, last_name, job_title
FROM employees
WHERE department_id = 101;

# Objective: Find the total sales and average order value for a specific product category

SELECT category, SUM(sales_amount) AS total_sales, AVG(order_value) AS avg_order_value
FROM sales
WHERE category = 'Electronics'
GROUP BY category;


# Objective: Get details of customers who made a purchase in the last month, along with their order information.

SELECT customers.customer_id, customers.customer_name, orders.order_id, orders.order_date
FROM customers
JOIN orders ON customers.customer_id = orders.customer_id
WHERE orders.order_date >= '2023-10-01' AND orders.order_date < '2023-11-01';


# Objective: Identify patterns in product sales by analyzing monthly sales data.

SELECT EXTRACT(MONTH FROM order_date) AS month, COUNT(*) AS order_count
FROM orders
GROUP BY month
ORDER BY month;


# Objective: Check for missing information in a critical table.

SELECT *
FROM important_table
WHERE required_field IS NULL;


# Objective: Find the top-performing salespeople based on their total sales.

SELECT salesperson_id, SUM(sales_amount) AS total_sales
FROM sales
GROUP BY salesperson_id
ORDER BY total_sales DESC
LIMIT 5;


# Objective: Analyze trends in customer sign-ups over the past year.

SELECT EXTRACT(MONTH FROM signup_date) AS month, COUNT(*) AS signups
FROM customers
WHERE signup_date >= '2022-11-01'
GROUP BY month
ORDER BY month;


# Objective: Find all orders containing a specific product.
SELECT orders.order_id, order_items.product_name, order_items.quantity
FROM orders
JOIN order_items ON orders.order_id = order_items.order_id
WHERE order_items.product_name = 'Smartphone';


# Objective: Identify and delete duplicate records from a table.


DELETE FROM my_table
WHERE rowid NOT IN (
    SELECT MIN(rowid)
    FROM my_table
    GROUP BY unique_column
);


# Objective: Calculate the average salary for each department, excluding salaries above a certain threshold.

SELECT department_id, AVG(salary) AS avg_salary
FROM employees
WHERE salary < 100000
GROUP BY department_id;


# Objective: Calculate the total revenue generated by each product category.

SELECT category, SUM(sales_amount) AS total_revenue
FROM sales
GROUP BY category;



